# Generated by Django 5.1.5 on 2025-01-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='Flight',
        ),
    ]
