# Generated by Django 5.1.5 on 2025-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='flight',
            field=models.ManyToManyField(related_name='passengers', to='flights.flight'),
        ),
    ]
